frr version 10.5.1
frr defaults traditional
hostname r7
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.67.2/30
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.78.1/30
 ip ospf network point-to-point
!
router ospf
 ospf router-id 7.7.7.7
 network 10.0.67.0/30 area 0.0.0.0
 network 10.0.78.0/30 area 0.0.0.0
!
line vty
!
